---
author: "TODO"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::knitr}
  %\VignetteIndexEntry{Example of Trackframe vs move2 performance}
---

# Example of Trackframe vs move2 performance

```{r}
library(trackframe)
```


Distance function for trackframe.

```{r}
library(units)
tf_distance <- function(tf) {
  x <- set_units(
    c(sqrt(diff(easting(tf)[[1]]) ^ 2 + diff(northing(tf)[[1]])^2), NA),
    'm'
  )
  x[which(
    tf[1:(nrow(tf) - 1) ,attr(tf, 'id')][[1]] !=
      tf[2:nrow(tf), attr(tf, 'id')][[1]]
  )] <- NA
  x
}
filter_nonempty <- function(x) x[!sf::st_is_empty(x),]
```

Load data

```{r, results="hide"}
library(move2)
suppressPackageStartupMessages(library(move2, quietly = TRUE))
albatross_move2 <- mt_read(mt_example()) |>
  sf::st_transform(3857) |>
  filter_nonempty()

suppressPackageStartupMessages(library(trackframe, quietly = TRUE))
albatross_tf <- as.track_frame(albatross_move2)
```

```{r}
brock_mt_distance <- function(m2) {
  coords <- sf::st_coordinates(m2)
  x <- sqrt(diff(coords[,1])^2 + diff(coords[,2])^2)
  x[diff(as.numeric(mt_track_id(albatross_move2))) != 0] <- NA
  set_units(c(x, NA), 'm')
}
all.equal(brock_mt_distance(albatross_move2), mt_distance(albatross_move2), check.attributes = FALSE)
```

Check that the distance functions output the same result:
```{r}
all.equal(mt_distance(albatross_move2), tf_distance(albatross_tf), check.attributes = FALSE)
```

Compare performance

```{r}
library(microbenchmark)
m <- microbenchmark(
  brock_mt_distance(albatross_move2),
  mt_distance(albatross_move2),
  times = 15
)
m
plot(m)
```



